[build]
  # No necesitas estas configuraciones si solo tienes funciones serverless
  # publish = "dist"
  # command = "npm run build" (o cualquier comando de build)

[functions]
  directory = "netlify/functions" # Este debe ser el directorio de tus funciones
  node_bundler = "esbuild"